<?php

/**
 * @file
 * Bootstrap sub-theme.
 *
 * Place your custom PHP code in this file.
 */

/**
* Implements hook_preprocess_node
*/
function arun_preprocess_node(&$variables) {
  // Getting the node creation time stamp from the node object.
  $date = $variables['node']->getCreatedTime();
  // Here you can use drupal's format_date() function, or some custom PHP date formatting.
  $variables['date'] = \Drupal::service('date.formatter')->format($date, 'long');
}
